### ISSUE TITLE
version 0.9.9 and maven central

### ISSUE THREAD

**Issue by programingjd** [fluidsonic/fluid-mongo#2]
Did you forget to push version 0.9.9 to maven central ?

**Comment by fluidsonic** [comment]
Hey. Unfortunately publishing to Maven Central gets more and more complicated and unreliable. Sometimes I have to publish a dozen times to finally get over the dreaded read timeouts.
Meanwhile all libraries are available on https://dl.bintray.com/fluidsonic/maven/ too.

I'll likely pull all libraries from Maven Central if I cannot find a good solution. I'm still trying to set up auto-publishing to Maven Central from Bintray but that isn't easy either.

**Comment by fluidsonic** [comment]
I have updated the README accordingly.

**Comment by programingjd** [comment]
How about publishing to jcenter then ? Especially since you are already using bintray.

**Comment by fluidsonic** [comment]
JCenter sync also failed for me on Bintray. I was trying to use it because from there Bintray can sync to Maven Central.
I didn't have time to investigate that issue either but it's also planned.

**Comment by fluidsonic** [comment]
0.9.10 is now available on JCenter and Maven Central 🙂
